# Generated by Django 3.0 on 2023-03-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20221020_0858'),
        ('myapp', '0004_auto_20230323_0828'),
    ]

    operations = [
    ]
