# Generated by Django 3.0 on 2023-03-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20230327_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ordersist',
            new_name='OrderList',
        ),
    ]
