# Generated by Django 3.0 on 2023-03-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20230327_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpending',
            old_name='orderi',
            new_name='orderid',
        ),
    ]
