# Generated by Django 3.0 on 2023-03-27 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20230327_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlist',
            old_name='orderid',
            new_name='orderid1',
        ),
        migrations.RenameField(
            model_name='orderpending',
            old_name='orderid',
            new_name='orderid1',
        ),
    ]
