# Generated by Django 3.0 on 2023-03-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20230327_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='sliptime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderpending',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
