# Generated by Django 3.0 on 2023-03-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20230328_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='trackingnumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
